spring.datasource.url=jdbc:postgresql://localhost:5433/pizzaria_estoque
spring.datasource.username=nostra
spring.datasource.password=nostra123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=ZXN0b3F1ZS1hcGktcGl6emFyaWEtbm9zdHJhLXNlY3JldC1rZXktdGhhdC1pcy1sb25nLWVub3VnaC1mb3ItaHM1MTI=
jwt.expiration-ms=3600000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.security.web=TRACE
spring.security.filter.dispatcher-types=request